version: '3'

services:
    discordbot:
        image: 192.168.1.136:9005/dolores:latest
        container_name: dolores
        environment:
            - DiscordBotCommandPrefix=/
            - DiscordKey=
            - DiscordWebhookUrl=
            - RocketLaunchLiveAPIKey=
            - NasaAPIKey=
            - RussianLossesWebhook=
            - RussianLossesRuntime=7:2:0
        restart: unless-stopped